/*
 * Secret Server
 *
 * This is an API of a secret service. You can save your secret by using the API. You can restrict the access of a secret after the certen number of views or after a certen period of time.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"fmt"
	"log"
	"net/http"
	"os"

	sw "git.dwarvesf.com/secret-server/goapi/src/go"

	_ "github.com/jinzhu/gorm/dialects/mysql"
)

func validate(err error) {
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
}

func main() {
	log.Printf("Server started")

	// t := time.Now().Local()

	// fmt.Println(t)

	// s := time.Now().Local().Add(24 * time.Hour)

	// fmt.Println(s)

	validate(sw.Init())

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
